prjCadastrodeAluno/src/br/com/fatec/cadastro/view/AlunoMB.java


package br.com.fatec.cadastro.view;


import java.io.Serializable;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import br.com.fatec.cadastro.business.AlunoBusiness;
import br.com.fatec.cadastro.business.AlunoBusiness.MensagemEnum;
import br.com.fatec.cadastro.model.Aluno;
import br.com.fatec.cadastro.util.JSFUtil;

@ManagedBean
@ViewScoped
public class AlunoMB implements Serializable{

	private static final long serialVersionUID = 1L;
	private Aluno aluno = new Aluno();
	AlunoBusiness ab = new AlunoBusiness();

	public Aluno getAluno() {
		return aluno;
	}

	public void setAluno(Aluno aluno) {
		this.aluno= aluno;
	}

	public void salvar() {
			
		if(ab.salvarAluno(aluno) == MensagemEnum.SUCESSO){
			System.out.println("Sucesso!");	
			aluno = new Aluno();
		}
		else{
			System.out.println("Erro!");
		}
		
		JSFUtil.addMessage("br.com.fatec.cadastro.controller.AlunoMB.idMensagem",ab.getMsg());
		
		
	}
	
	public List<Aluno> getAlunos()
	{
		 return ab.getAllAlunos();
		
	}

}

prjCadastrodeAluno/src/br/com/fatec/cadastro/view/CursoMB.java


package br.com.fatec.cadastro.view;


import java.io.Serializable;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import br.com.fatec.cadastro.business.CursoBusiness;
import br.com.fatec.cadastro.business.CursoBusiness.MensagemEnum;
import br.com.fatec.cadastro.model.Curso;
import br.com.fatec.cadastro.util.JSFUtil;

@ManagedBean
@ViewScoped
public class CursoMB implements Serializable{

	private static final long serialVersionUID = 1L;
	private Curso curso = new Curso();
	CursoBusiness cb = new CursoBusiness();

	public Curso getCurso() {
		return curso;
	}

	public void setCurso(Curso curso) {
		this.curso= curso;
	}

	public void salvar() {
			
		if(cb.salvarCurso(curso) == MensagemEnum.SUCESSO){
			System.out.println("Sucesso!");	
			curso = new Curso();
		}
		else{
			System.out.println("Erro!");
		}
		
		JSFUtil.addMessage("br.com.fatec.cadastro.controller.CursoMB.idMensagem",cb.getMsg());
		
		
	}
	
	public List<Curso> getCursos()
	{
		 return cb.getAllCursos();
		
	}

}

prjCadastrodeAluno/src/br/com/fatec/cadastro/view/DisciplinaMB.java


package br.com.fatec.cadastro.view;


import java.io.Serializable;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import br.com.fatec.cadastro.business.DisciplinaBusiness;
import br.com.fatec.cadastro.business.DisciplinaBusiness.MensagemEnum;
import br.com.fatec.cadastro.model.Disciplina;
import br.com.fatec.cadastro.util.JSFUtil;

@ManagedBean
@ViewScoped
public class DisciplinaMB implements Serializable{

	private static final long serialVersionUID = 1L;
	private Disciplina disciplina = new Disciplina();
	DisciplinaBusiness db = new DisciplinaBusiness();

	public Disciplina getDisciplina() {
		return disciplina;
	}

	public void setDisciplina(Disciplina disciplina) {
		this.disciplina= disciplina;
	}

	public void salvar() {
			
		if(db.salvarDisciplina(disciplina) == MensagemEnum.SUCESSO){
			System.out.println("Sucesso!");	
			disciplina = new Disciplina();
		}
		else{
			System.out.println("Erro!");
		}
		
		JSFUtil.addMessage("br.com.fatec.cadastro.controller.DisciplinaMB.idMensagem",db.getMsg());
		
		
	}
	
	public List<Disciplina> getDisciplinas()
	{
		 return db.getAllDisciplinas();
		
	}

}

prjCadastrodeAluno/src/br/com/fatec/cadastro/view/ModalidadeMB.java
package br.com.fatec.cadastro.view;

import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;

import br.com.fatec.cadastro.model.Modalidade;

@ManagedBean
@ApplicationScoped
public class ModalidadeMB {
	
	private Modalidade selectedModalidade;
	
	
	
	public Modalidade getSelectedModalidade() {
		return selectedModalidade;
	}



	public void setSelectedModalidade(Modalidade selectedModalidade) {
		this.selectedModalidade = selectedModalidade;
	}



	public Modalidade[] getModalidades(){
		return Modalidade.values();
	}
}

prjCadastrodeAluno/WebContent/pages/alunoGerenciar.xhtml
<ui:composition template="templateMenu.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:tm="http://java.sun.com/jsf/composite/terminal/1_0/components">
	

	<ui:define name="title">
		<h:outputText value="#{msg['pages.alunoGerenciar.aluno.title']}" />
	</ui:define>
	

	<ui:define name="principal">
		 <h:form id="alunoForm">
	    
	     <p:growl id="msg" showDetail="true" life="3000"/>   
	         
	     <p:panelGrid columns="4"> 
	     	   <f:facet name="header">
        			<p:outputLabel value="#{msg['pages.alunoGerenciar.aluno.title']}"/>			
    		   </f:facet>
	          
	           <p:outputLabel value="#{msg['pages.alunoGerenciar.aluno.ra']}"/>
	           <p:inputText   value="#{alunoMB.aluno.ra}" id="raAluno"/>
			
			   <p:outputLabel value="#{msg['pages.alunoGerenciar.aluno.nome']}"/>
	           <p:inputText   value="#{alunoMB.aluno.nome}" id="nomeAluno"/>
	           
	           <p:outputLabel value="#{msg['pages.alunoGerenciar.aluno.cpf']}"/>
	           <p:inputText   value="#{alunoMB.aluno.cpf}" id="cpfAluno"/>
	           
	           <p:outputLabel value="#{msg['pages.alunoGerenciar.aluno.rg']}"/>
	           <p:inputText   value="#{alunoMB.aluno.rg}" id="rgAluno"/>
	           
	           <p:outputLabel value="#{msg['pages.alunoGerenciar.aluno.dataNasc']}"/>
	           <p:inputText   value="#{alunoMB.aluno.dataNasc}" id="dataNascAluno"/>
	           
	           <p:outputLabel value="#{msg['pages.alunoGerenciar.aluno.endereco']}"/>
	           <p:inputText   value="#{alunoMB.aluno.endereco}" id="enderecoAluno"/>

	           <p:commandButton  actionListener="#{alunoMB.salvar}" value="#{msg['pages.alunoGerenciar.aluno.btnSalvar']}" update="msg, alunoForm, :tableAlunos"  ></p:commandButton>
               <p:commandButton                                       value="#{msg['pages.alunoGerenciar.aluno.btnFechar']}" action="inicio"></p:commandButton>
               
	     </p:panelGrid>
	     </h:form>

	     <p:dataTable value="#{alunoMB.alunos}" var="aluno" id="tableAlunos">
	         <p:column headerText="#{msg['pages.alunoGerenciar.aluno.ra']}">
	                   <p:outputLabel value="#{aluno.ra}"/>
	         </p:column>
	     
	     	<p:column headerText="#{msg['pages.alunoGerenciar.aluno.nome']}">
	             <p:outputLabel value="#{aluno.nome}"/>
	        </p:column>
	        
	        <p:column headerText="#{msg['pages.alunoGerenciar.aluno.cpf']}">
	             <p:outputLabel value="#{aluno.cpf}"/>
	        </p:column>
	        
	        <p:column headerText="#{msg['pages.alunoGerenciar.aluno.rg']}">
	             <p:outputLabel value="#{aluno.rg}"/>
	        </p:column>
	        
	        <p:column headerText="#{msg['pages.alunoGerenciar.aluno.dataNasc']}">
	             <p:outputLabel value="#{aluno.dataNasc}"/>
	        </p:column>
	        
	        <p:column headerText="#{msg['pages.alunoGerenciar.aluno.endereco']}">
	             <p:outputLabel value="#{aluno.endereco}"/>
	        </p:column>
	     
	     </p:dataTable>
	     	
	</ui:define>
</ui:composition>







prjCadastrodeAluno/WebContent/pages/cursoGerenciar.xhtml
<ui:composition template="templateMenu.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:tm="http://java.sun.com/jsf/composite/terminal/1_0/components">
	

	<ui:define name="title">
		<h:outputText value="#{msg['pages.cursoGerenciar.curso.title']}" />
	</ui:define>
	

	<ui:define name="principal">
		 <h:form id="cursoForm">
	    
	     <p:growl id="msg" showDetail="true" life="3000"/>   
	         
	     <p:panelGrid columns="2"> 
	     	   <f:facet name="header">
        			<p:outputLabel value="#{msg['pages.cursoGerenciar.curso.title']}"/>			
    		   </f:facet>
	          
	           <p:outputLabel value="#{msg['pages.cursoGerenciar.curso.codigoCur']}"/>
	           <p:inputText   value="#{cursoMB.curso.codigoCur}" id="codigoCur"/>
			
			   <p:outputLabel value="#{msg['pages.cursoGerenciar.curso.nome']}"/>
	           <p:inputText   value="#{cursoMB.curso.nome}" id="nomecur"/>
	           
	           <p:outputLabel value="#{msg['pages.cursoGerenciar.curso.duracao']}"/>
	           <p:inputText   value="#{cursoMB.curso.duracao}" id="duracao"/>
	           
	            <p:selectOneMenu value="#{modalidadeMB.selectedModalidade}" id="modalidade">
    			
    			<f:selectItems value="#{modalidadeMB.modalidades}" var="modalidade"
    				 itemLabel="#{modalidade.label}" 
    				 itemValue="#{modalidade}"/>  <!--  MODARRRRR -->
			</p:selectOneMenu>      
	           
	         
            
           <!--  <p:selectOneMenu value="#{modalidadeMB.selectedModalidade}" id="modalidade">
    			
    			<f:selectItems value="#{modalidadeMB.modalidades}" var="modalidade"
    				 itemLabel="#{modalidade.label}" 
    				 itemValue="#{modalidade}"/>
			</p:selectOneMenu>
			-->
            
             
	           
	            

	           <p:commandButton  actionListener="#{cursoMB.salvar}" value="#{msg['pages.cursoGerenciar.curso.btnSalvar']}" update="msg, cursoForm, :tableCurso"  ></p:commandButton>
               <p:commandButton                                       value="#{msg['pages.cursoGerenciar.curso.btnFechar']}" action="inicio"></p:commandButton>
               
	     </p:panelGrid>
	     </h:form>

	     <p:dataTable value="#{cursoMB.cursos}" var="curso" id="tableCurso">
	         <p:column headerText="#{msg['pages.cursoGerenciar.curso.codigoCur']}">
	                   <p:outputLabel value="#{curso.codigoCur}"/>
	         </p:column>
	     
	     	<p:column headerText="#{msg['pages.cursoGerenciar.curso.nome']}">
	             <p:outputLabel value="#{curso.nome}"/>
	        </p:column>
	        
	        <p:column headerText="#{msg['pages.cursoGerenciar.curso.duracao']}">
	             <p:outputLabel value="#{curso.duracao}"/>
	        </p:column>
	        
	        <p:column headerText="#{msg['pages.cursoGerenciar.curso.modalidade']}">
	             <p:outputLabel value="#{curso.modalidade}"/>
	        </p:column> 
	     
	     </p:dataTable>
	     	
	</ui:define>
</ui:composition>

prjCadastrodeAluno/WebContent/pages/disciplinaGerenciar.xhtml
<ui:composition template="templateMenu.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:tm="http://java.sun.com/jsf/composite/terminal/1_0/components">
	

	<ui:define name="title">
		<h:outputText value="#{msg['pages.disciplinaGerenciar.disciplina.title']}" />
	</ui:define>
	

	<ui:define name="principal">
		 <h:form id="disciplinaForm">
	    
	     <p:growl id="msg" showDetail="true" life="3000"/>   
	         
	     <p:panelGrid columns="2"> 
	     	   <f:facet name="header">
        			<p:outputLabel value="#{msg['pages.disciplinaGerenciar.disciplina.title']}"/>			
    		   </f:facet>
	          
	           <p:outputLabel value="#{msg['pages.disciplinaGerenciar.disciplina.codigoDis']}"/>
	           <p:inputText   value="#{disciplinaMB.disciplina.codigoDis}" id="codigoDis"/>
			
			   <p:outputLabel value="#{msg['pages.disciplinaGerenciar.disciplina.nome']}"/>
	           <p:inputText   value="#{disciplinaMB.disciplina.nome}" id="nomeDisc"/>
	           
	           <p:outputLabel value="#{msg['pages.disciplinaGerenciar.disciplina.cargaHr']}"/>
	           <p:inputText   value="#{disciplinaMB.disciplina.cargaHr}" id="cargaHr"/>
	           

	           <p:commandButton  actionListener="#{disciplinaMB.salvar}" value="#{msg['pages.disciplinaGerenciar.disciplina.btnSalvar']}" update="msg, disciplinaForm, :tableDisciplina"  ></p:commandButton>
               <p:commandButton                                       value="#{msg['pages.disciplinaGerenciar.disciplina.btnFechar']}" action="inicio"></p:commandButton>
               
	     </p:panelGrid>
	     </h:form>

	     <p:dataTable value="#{disciplinaMB.disciplinas}" var="disciplina" id="tableDisciplina">
	         <p:column headerText="#{msg['pages.disciplinaGerenciar.disciplina.codigoDis']}">
	                   <p:outputLabel value="#{disciplina.codigoDis}"/>
	         </p:column>
	     
	     	<p:column headerText="#{msg['pages.disciplinaGerenciar.disciplina.nome']}">
	             <p:outputLabel value="#{disciplina.nome}"/>
	        </p:column>
	        
	        <p:column headerText="#{msg['pages.disciplinaGerenciar.disciplina.cargaHr']}">
	             <p:outputLabel value="#{disciplina.cargaHr}"/>
	        </p:column>
	     
	     </p:dataTable>
	     	
	</ui:define>
</ui:composition>

prjCadastrodeAluno/WebContent/pages/inicio.xhtml
<ui:composition template="templateMenu.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:tm="http://java.sun.com/jsf/composite/terminal/1_0/components">
	
	<ui:define name="title">
		<h:outputText value="#{msg['pages.inicio.title']}" />
	</ui:define>

	<ui:define name="principal">
	     <p:outputLabel value="#{msg['pages.inicio.welcome']}"/>      	
	</ui:define>

	
</ui:composition>

prjCadastrodeAluno/WebContent/pages/templateMenu.xhtml
<!DOCTYPE html>
<h:html
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<f:view encoding="ISO-8859-1">
	<h:head>
		<title><ui:insert name="title">
				<h:outputLabel value="#{msg['pages.templateMenu.titleMainMenu']}" />
			</ui:insert></title>
	</h:head>
	
	<h:body style="font-size: 12px">

		<p:layout id="globalLayout"   fullPage="true">
			
		
			<p:layoutUnit position="north" size="160" >
				<ui:include src="comuns/cabecalho.xhtml" />
			</p:layoutUnit>

			
			<p:layoutUnit position="south">
				<ui:include src="comuns/rodape.xhtml" />
			</p:layoutUnit>


			<!-- Menu lateral -->
			<p:layoutUnit position="west" header="#{msg['pages.templateMenu.titleMainMenu']}"
				collapsible="true" size="220">
				<ui:include src="comuns/menuLateral.xhtml" />
			</p:layoutUnit>

	
			<p:layoutUnit position="center">
				<ui:insert name="principal" />
			</p:layoutUnit>
		</p:layout>

	</h:body>
</f:view>
</h:html>